# ==============================================================================
# 🚀 Kaggle Devices — NVIDIA T4 GPU
# ------------------------------------------------------------------------------
# Purpose:
#   - Kaggle default GPU runtime (T4, 16 GB).
#   - Configures AMP and runtime guardrails for 9-hour walltime.
# ==============================================================================

_target_: torch.device
devices: 1
precision: 16-mixed
deterministic: true
cudnn_benchmark: true
timeout_hours: 9
notes: "Kaggle GPU quota: T4 runtime, ~9h max walltime."
