# Ruff configuration for SpectraMind V50

line-length = 100
target-version = "py311"

[lint]
# Enable core rules + import sorting (so you can eventually drop isort)
select = ["E", "F", "I", "B", "UP", "C90"]
ignore = []

# Exclude large/artifact dirs
exclude = [
  ".git",
  ".venv",
  "venv",
  "data",
  "outputs",
  "logs",
  "build",
  "dist",
]

[lint.isort]
profile = "black"
line-length = 100
known-first-party = ["spectramind", "src"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false