# Ruff configuration for SpectraMind V50

# Enable Ruff formatter (works with the ruff-format pre-commit hook)
line-length = 100
indent-width = 4
target-version = "py311"

[lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort (import ordering via Ruff)
  "B",   # flake8-bugbear
  "UP",  # pyupgrade
  "C90"  # mccabe complexity
]
ignore = [
  # add rule codes here to temporarily silence specific checks, if needed
]

[lint.isort]
known-first-party = ["spectramind", "src"]
profile = "black"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false