# ------------------------------------------------------------------------------
# docker-compose.yml — SpectraMind V50 (ArielSensorArray)
# One‑command dev/runtime with GPU/CPU profiles, live docs, TensorBoard, and CI.
#
#  Build all images:        docker compose build
#  GPU shell:               docker compose --profile gpu up -d spectramind-gpu && \
#                           docker compose exec spectramind-gpu bash
#  CPU shell:               docker compose --profile cpu up -d spectramind-cpu && \
#                           docker compose exec spectramind-cpu bash
#  Live docs:               docker compose --profile docs up docs
#  TensorBoard:             docker compose --profile viz up tensorboard
#  CI (headless):           docker compose --profile ci up --abort-on-container-exit ci
#
# Notes
#  • All services mount the repo at /workspace (Poetry + Typer CLI ready).
#  • GPU via NVIDIA Container Toolkit (device_requests); CPU services run without it.
#  • Caches (pip/poetry/HF) are persisted in named volumes to speed up builds.
#  • Align with .dockerignore / .gitignore / .dvcignore to keep images lean.
#  • To avoid root-owned files on host, uncomment the user: lines (requires matching UID/GID).
# ------------------------------------------------------------------------------

version: "3.9"

# ---------- Reusable snippets --------------------------------------------------
x-common-env: &common-env
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"
  PYTHONUNBUFFERED: "1"
  POETRY_VIRTUALENVS_CREATE: "false"
  # Headless-safe Matplotlib
  MPLBACKEND: Agg
  # Hugging Face caches (aligned with .dockerignore)
  TRANSFORMERS_CACHE: /workspace/.hf_cache
  HF_HOME: /workspace/.hf_cache
  # Optional: deterministic hashing (helps CI reproducibility)
  PYTHONHASHSEED: "0"

# If you keep secrets/API keys in an .env, uncomment:
# x-common-envfile: &common-envfile
#   - .env

x-common-volumes: &common-volumes
  - ./:/workspace
  - pip-cache:/root/.cache/pip
  - poetry-cache:/root/.cache/pypoetry
  - spectramind-cache:/root/.cache
  - hf-cache:/workspace/.hf_cache
  # Optional: persist logs and outputs separately
  # - logs:/workspace/logs
  # - outputs:/workspace/outputs

x-common-logging: &common-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

x-hc-poetry: &hc-poetry
  interval: 10s
  timeout: 5s
  retries: 15
  start_period: 15s
  test: ["CMD-SHELL","poetry --version >/dev/null 2>&1 || exit 1"]

x-hc-cli: &hc-cli
  interval: 20s
  timeout: 5s
  retries: 10
  start_period: 20s
  test: ["CMD-SHELL","python -c 'import importlib; importlib.import_module(\"spectramind\")' >/dev/null 2>&1 || exit 1"]

# ---------- Services -----------------------------------------------------------
services:
  # ----------------------------------------------------------------
  # GPU dev image & interactive shell
  # ----------------------------------------------------------------
  spectramind-gpu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # CUDA runtime image with cuDNN (tuned in Dockerfile by BASE_IMAGE)
        BASE_IMAGE: ${GPU_BASE_IMAGE:-nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04}
        POETRY_VERSION: ${POETRY_VERSION:-1.8.3}
        # Torch wheel index for CUDA 12.1 (empty for CPU)
        TORCH_WHL_INDEX: ${TORCH_WHL_INDEX:-https://download.pytorch.org/whl/cu121}
    image: spectramindv50:gpu
    container_name: spectramind-gpu
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: bash
    shm_size: "16gb"
    environment:
      <<: *common-env
      # Prefer device_requests, fallback deploy.resources for Swarm-like runtimes
      NVIDIA_VISIBLE_DEVICES: ${NVIDIA_VISIBLE_DEVICES:-all}
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    volumes: *common-volumes
    device_requests:
      - driver: "nvidia"
        count: -1
        capabilities: ["gpu"]
    healthcheck: *hc-poetry
    logging: *common-logging
    # user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    profiles: ["gpu"]

  # ----------------------------------------------------------------
  # CPU dev image & interactive shell (slim base, no CUDA)
  # ----------------------------------------------------------------
  spectramind-cpu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${CPU_BASE_IMAGE:-python:3.11-slim}
        POETRY_VERSION: ${POETRY_VERSION:-1.8.3}
        TORCH_WHL_INDEX: ""   # ensure CPU wheels resolve
    image: spectramindv50:cpu
    container_name: spectramind-cpu
    working_dir: /workspace
    tty: true
    stdin_open: true
    command: bash
    shm_size: "8gb"
    environment: *common-env
    volumes: *common-volumes
    healthcheck: *hc-poetry
    logging: *common-logging
    # user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    profiles: ["cpu"]

  # ----------------------------------------------------------------
  # Live docs server (MkDocs) — http://localhost:8000
  # Uses GPU image by default; switch to cpu image by setting DOCS_IMAGE
  # ----------------------------------------------------------------
  docs:
    image: ${DOCS_IMAGE:-spectramindv50:gpu}
    container_name: spectramind-docs
    working_dir: /workspace
    command: bash -lc "poetry run mkdocs serve -a 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment: *common-env
    volumes: *common-volumes
    depends_on:
      spectramind-gpu:
        condition: service_started
    healthcheck:
      <<: *hc-poetry
      test: ["CMD-SHELL","curl -fsS http://localhost:8000/ >/dev/null || exit 1"]
    logging: *common-logging
    restart: unless-stopped
    profiles: ["docs"]

  # ----------------------------------------------------------------
  # TensorBoard — http://localhost:6006
  # ----------------------------------------------------------------
  tensorboard:
    image: ${TB_IMAGE:-spectramindv50:gpu}
    container_name: spectramind-tb
    working_dir: /workspace
    command: bash -lc "poetry run tensorboard --logdir logs --host 0.0.0.0 --port 6006"
    ports:
      - "6006:6006"
    environment: *common-env
    volumes:
      - ./:/workspace
      - pip-cache:/root/.cache/pip
      - poetry-cache:/root/.cache/pypoetry
      - spectramind-cache:/root/.cache
      - hf-cache:/workspace/.hf_cache
      - tb-logs:/workspace/logs
    depends_on:
      spectramind-gpu:
        condition: service_started
    healthcheck:
      <<: *hc-poetry
      test: ["CMD-SHELL","curl -fsS http://localhost:6006/ >/dev/null || exit 1"]
    logging: *common-logging
    restart: unless-stopped
    profiles: ["viz"]

  # ----------------------------------------------------------------
  # Headless CI runner (deterministic, non‑interactive)
  # Runs 'make ci' or Makefile.ci if present. Exits on completion.
  # ----------------------------------------------------------------
  ci:
    image: ${CI_IMAGE:-spectramindv50:cpu}
    container_name: spectramind-ci
    working_dir: /workspace
    command: bash -lc 'if [ -f makefile.ci ] || [ -f Makefile.ci ]; then make -f makefile.ci ci || make -f Makefile.ci ci; else make ci; fi'
    environment:
      <<: *common-env
      SPECTRAMIND_CI: "1"
      DEVICE: "${DEVICE:-cpu}"
      EPOCHS: "${EPOCHS:-1}"
    volumes: *common-volumes
    # For CI flows that build images first:
    # depends_on:
    #   spectramind-cpu:
    #     condition: service_started
    healthcheck: *hc-cli
    logging: *common-logging
    restart: "no"
    profiles: ["ci"]

# ---------- Volumes ------------------------------------------------------------
volumes:
  pip-cache:
  poetry-cache:
  spectramind-cache:
  hf-cache:
  tb-logs:
  # logs:
  # outputs:
