# ==============================================================================
# dvc.yaml — SpectraMind V50 (ArielSensorArray)
# ------------------------------------------------------------------------------
# Declarative pipeline for reproducible runs:
#   • From raw Ariel telescope frames → calibrated light curves → μ/σ spectra
#   • Physics-informed training (Mamba SSM + GNN)
#   • Symbolic + SHAP diagnostics, FFT/UMAP/t-SNE overlays
#   • Submission packaging for Kaggle CI
#
# Run:
#   dvc repro                # rebuild full pipeline
#   dvc exp run              # run an experiment
#   dvc plots diff           # compare metrics between runs
# ==============================================================================

stages:
  # ------------------------------------------------------------------
  calibrate:
    cmd: >
      poetry run spectramind calibrate
        --input data/raw
        --output data/calibrated
        --log logs/calibration.log
    deps:
      - data/raw
      - configs/calibration.yaml
      - src/pipeline/calibration_pipeline.py
    outs:
      - data/calibrated
    metrics:
      - logs/calibration.json
    plots:
      - logs/calibration_plots/*.png

  # ------------------------------------------------------------------
  train:
    cmd: >
      poetry run spectramind train
        --config configs/config_v50.yaml
        --data data/calibrated
        --out outputs/model
    deps:
      - data/calibrated
      - configs/config_v50.yaml
      - src/train/train_v50.py
      - src/models/fgs1_mamba.py
      - src/models/airs_gnn.py
      - src/models/multi_scale_decoder.py
    outs:
      - outputs/model
    metrics:
      - outputs/model/metrics.json
    plots:
      - outputs/model/loss_curve.png

  # ------------------------------------------------------------------
  predict:
    cmd: >
      poetry run spectramind predict
        --model outputs/model
        --data data/calibrated
        --out outputs/predictions
    deps:
      - outputs/model
      - src/predict/predict_v50.py
    outs:
      - outputs/predictions
    metrics:
      - outputs/predictions/summary.json

  # ------------------------------------------------------------------
  diagnostics:
    cmd: >
      poetry run spectramind diagnose dashboard
        --pred outputs/predictions
        --out outputs/diagnostics
        --html outputs/diagnostics/report.html
    deps:
      - outputs/predictions
      - src/diagnostics/generate_html_report.py
      - src/diagnostics/generate_diagnostic_summary.py
      - src/diagnostics/shap_overlay.py
      - src/diagnostics/plot_umap_v50.py
      - src/diagnostics/plot_tsne_interactive.py
      - src/diagnostics/symbolic_influence_map.py
    outs:
      - outputs/diagnostics
    metrics:
      - outputs/diagnostics/diagnostic_summary.json
    plots:
      - outputs/diagnostics/*.png
      - outputs/diagnostics/*.html

  # ------------------------------------------------------------------
  submit:
    cmd: >
      poetry run spectramind submit
        --pred outputs/predictions
        --bundle outputs/submission/bundle.zip
        --meta outputs/submission/manifest.json
    deps:
      - outputs/predictions
      - src/cli/cli_submit.py
    outs:
      - outputs/submission/bundle.zip
      - outputs/submission/manifest.json
    metrics:
      - outputs/submission/manifest.json
