# Top-level calibration config
# Default = temperature scaling; switch to COREL via: method=corel

defaults:
  - method: temperature
  - override hydra/job_logging: default
  - override hydra/run_logging: default

# Common I/O
preds_pt: "outputs/preds.pt"                  # input μ,σ
targets_pt: null                              # optional (N,B) ground truth
ids_path: null                                # optional list of planet_ids
out_csv: "outputs/submission_calibrated.csv"  # submission (μ only)
out_pt: "outputs/preds_calibrated.pt"         # calibrated σ (+T)
report_html: "outputs/diagnostics/calib_report.html"

# Runtime
device: "cpu"       # or "cuda"
seed: 1337
bins: 283

# Method dispatch (populated by method/*)
method: ???         # "temperature" | "corel"