# .github/ISSUE_TEMPLATE/security_report.yml
# ==============================================================================
# SpectraMind V50 — Security Report (GitHub Issue Form)
# Purpose: capture vulnerabilities, supply-chain risks, or suspicious activity
# in a structured, coordinated disclosure–ready format.
# ==============================================================================

name: "🛡️ Security Report"
description: "Report a security vulnerability or suspicious activity affecting SpectraMind V50"
title: "[sec] <short summary>"
labels:
  - security
  - needs-triage
projects: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🛡️ Security Report — SpectraMind V50

        Thanks for helping keep the project and community safe.  
        **Do not** include secrets or active exploit payloads in this issue.  
        If sensitive details are required, please also contact the maintainers via **security@your-org.tld** for coordinated disclosure.

  # --- Report classification ---------------------------------------------------
  - type: dropdown
    id: report_type
    attributes:
      label: "Report Type"
      description: "What are you reporting?"
      options:
        - "Vulnerability (code or config)"
        - "Supply-chain / dependency risk"
        - "Credential leak / secret exposure"
        - "CI/CD misconfiguration"
        - "Infra / container hardening issue"
        - "Suspicious behavior / compromise indicators"
        - "Other (describe below)"
      default: 0
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "📝 Short Title"
      description: "Concise description of the issue."
      placeholder: "Example: Hardcoded token in submission workflow"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📄 Description"
      description: "What did you find? Why is it a problem? Include file/line links if possible."
      placeholder: |
        - Affected component(s): CLI, CI workflow, Dockerfile, configs/*
        - Vulnerable behavior: …
        - How it can be exploited / misused: …
        - References/CWE: CWE-79, CWE-200, etc.
    validations:
      required: true

  # --- Severity and impact -----------------------------------------------------
  - type: dropdown
    id: severity
    attributes:
      label: "Initial Severity (self-assessed)"
      options:
        - "Critical — practical remote exploit / secret exfiltration"
        - "High — privilege escalation or code execution with constraints"
        - "Medium — info leak, DoS, or weak isolation"
        - "Low — misconfig, best-practice gap, theoretical risk"
      default: 2

  - type: checkboxes
    id: impact
    attributes:
      label: "Potential Impact (select all)"
      options:
        - label: "Secrets exposure (tokens, keys, passwords)"
        - label: "Unauthorized code execution"
        - label: "Privilege escalation / lateral movement"
        - label: "Data loss or corruption"
        - label: "Submission tampering / leaderboard integrity"
        - label: "Supply-chain compromise (deps, actions, containers)"
        - label: "Service disruption (CI, DVC remotes, storage)"
        - label: "Privacy / PII exposure"
        - label: "Other (describe below)"

  # --- Reproducibility ---------------------------------------------------------
  - type: textarea
    id: repro
    attributes:
      label: "♻️ Reproduction Steps (safe / minimal)"
      description: "Exact steps to reproduce without causing harm. Prefer dry-run or redacted examples."
      render: bash
      placeholder: |
        1) git checkout <sha>
        2) spectramind <cmd> --dry-run …
        3) Observe: …

  - type: textarea
    id: scope
    attributes:
      label: "🧭 Affected Scope"
      description: "Repos/branches, files, workflows, images, or environments impacted."
      placeholder: |
        - Branches: main, release/*
        - Workflows: .github/workflows/submission.yml
        - Images: ghcr.io/org/spectramind:v50-cuda12.1
        - Paths: src/…, configs/…, Dockerfile

  - type: textarea
    id: env
    attributes:
      label: "🖥️ Environment"
      description: "Where observed (local, CI, Kaggle), OS/Kernel, container image digest, tool versions."
      placeholder: |
        - CI: GitHub Actions ubuntu-latest
        - Docker: ghcr.io/org/spectramind:v50@sha256:…
        - Python 3.12, PyTorch 2.3, CUDA 12.1
        - Hydra/DVC versions
        - Actions runner: 2025-08-20 build

  - type: input
    id: commit
    attributes:
      label: "🔒 Code Reference"
      description: "Commit SHA(s), tag(s), or PR(s) where the issue exists."
      placeholder: "e.g., 9a7b2f4, #2345"

  - type: textarea
    id: evidence
    attributes:
      label: "🧾 Evidence (redacted)"
      description: "Logs, screenshots, or scanner findings proving the issue. **Redact secrets.**"
      placeholder: |
        - trufflehog results (redacted)
        - grype / docker scout report
        - gh secret list vs workflow usage

  # --- Exploitation state ------------------------------------------------------
  - type: checkboxes
    id: exploitation
    attributes:
      label: "Has this been exploited?"
      options:
        - label: "No evidence of exploitation"
        - label: "Possibly (suspicious activity)"
        - label: "Confirmed (add details)"
        - label: "Unknown"

  - type: textarea
    id: indicators
    attributes:
      label: "🔎 Indicators of Compromise (IoCs)"
      description: "Hashes, IPs, domains, anomalous runs, or timestamps observed."
      placeholder: |
        - Unexpected workflow triggers at 2025-08-24T11:20Z
        - New PAT usage from unknown IP
        - Modified artifacts without matching CI run

  # --- Mitigation and disclosure -----------------------------------------------
  - type: textarea
    id: mitigation
    attributes:
      label: "🛠️ Proposed Mitigation / Containment"
      description: "Short-term containment + long-term fix ideas (least-privilege, rotation, pinning)."
      placeholder: |
        - Rotate compromised PAT
        - Restrict GH token permissions
        - Pin GitHub Actions to SHA
        - Add CODEOWNERS + required reviews
        - Add trufflehog/Gitleaks scans in CI
        - Harden Dockerfile (USER non-root)

  - type: textarea
    id: disclosure
    attributes:
      label: "🤝 Disclosure & Coordination"
      description: "Has anyone else been notified? Any embargo or disclosure window?"
      placeholder: |
        - Report sent to security@your-org.tld
        - Request 90-day coordinated disclosure window

  - type: textarea
    id: acceptance
    attributes:
      label: "✅ Acceptance Criteria"
      description: "Define ‘fixed’: scanner passes, configs hardened, reproducibility intact."
      placeholder: |
        - Secrets rotated & verified unused
        - CI jobs enforce secret scans & SBOM checks
        - Branch protection rules enforced
        - Dry-run repro no longer succeeds

  - type: checkboxes
    id: checklist
    attributes:
      label: "Pre-submit Checklist"
      options:
        - label: "No secrets or harmful payloads included"
          required: true
        - label: "Repro steps are safe/dry-run"
          required: true
        - label: "Provided commit/PR references"
        - label: "Included redacted evidence"
        - label: "Defined mitigation and acceptance criteria"