# configs/logger/tensorboard.yaml
# ==============================================================================
# 📊 TensorBoard Logger — SpectraMind V50
#
# Purpose
#   Configure TensorBoard logging for training and diagnostics.
#   Provides runtime-safe defaults for Kaggle/CI while enabling
#   rich local logging (scalars, histograms, graphs).
#
# Usage
#   In train.yaml:
#     defaults:
#       - logger: tensorboard
#
#   CLI override examples:
#     spectramind train logger=tensorboard logger.tensorboard.log_dir=logs/tb_runs
#     spectramind train logger=tensorboard logger.tensorboard.flush_secs=30
#
# Notes
#   • Keep I/O minimal in Kaggle mode (flush every few minutes).
#   • All logs are mirrored to logs/v50_debug_log.md for audit.
#   • Compatible with Lightning/Trainer or custom hooks.
#   • Hydra-safe: override any field at CLI (logger.tensorboard.<field>=<value>).
# ==============================================================================

tensorboard:
  enabled: true                      # Master switch

  # Output layout
  log_dir: "logs/tb_runs"            # Root dir for TB event files
  name: "spectramind_v50"            # Run name prefix (appended with timestamp/hash)
  version: null                      # Auto if null; set manually for reproducibility
  prefix: ""                         # Optional subdir prefix inside log_dir

  # Scalars, histograms, and graphs
  log_graph: false                   # Log model graph (overhead; set true if needed)
  histogram_freq: 0                  # 0 = disable; >0 = log histograms every N epochs
  write_images: false                # Log input images (expensive, off by default)
  default_hp_metric: false           # Avoid spurious hp_metric logging

  # Flush cadence / performance knobs
  flush_secs: 120                    # Seconds between async flushes
  max_queue: 10                      # Queue size before forcing flush
  workers: 1                         # DataLoader workers for summary writing

  # Audit trail
  audit_log_path: "logs/v50_debug_log.md"   # Mirror major TB events to Markdown audit log

  # Optional parallel loggers (compose with others via Hydra)
  extra_loggers: []                  # e.g. ["wandb", "mlflow"]

  # Kaggle runtime guardrails
  kaggle_safe:
    enabled: true
    flush_secs: 300                  # Throttle flushes to reduce I/O
    histogram_freq: 0                # Disable heavy histogram logging
    write_images: false              # Disable image writing
    log_graph: false                 # Graph logging off by default
    max_queue: 5                     # Smaller queue for constrained I/O

  # CI guardrails (disable or reduce logging in smoke runs)
  ci_fast:
    enabled: false                   # Disable TB logging in CI smoke tests
    flush_secs: 600                  # If enabled, flush infrequently
    histogram_freq: 0
    write_images: false
