# configs/model/constraints/lite.yaml
# ==============================================================================
# ⚖️ Physics Constraints — Lite Profile
# Minimal physical guidance for fastest convergence & Kaggle-safe runs
# ==============================================================================

constraints:
  enforce_nonnegativity: true
  smoothness_weight: 0.002                  # very light smoothing
  fft_smoothness_weight: 0.0005
  asymmetry_weight: 0.0002

  lensing:
    enabled: true
    bins: [120, 160]
    weight: 0.0005

  molecular_fingerprint:
    enabled: false                          # disable in lite mode
    molecules: []
    match_weight: 0.0
    false_positive_weight: 0.0

  calibration:
    nonnegativity_epsilon: 1.0e-8
    max_clip: 10.0                          # relaxed clamp

  diagnostics:
    log_violation_maps: false
    save_fft_plots: false
    export_json: null

  notes: |
    • Only enforces nonnegativity and very weak smoothness.
    • FFT/asymmetry/lensing applied at minimal weights.
    • Disables molecular priors for speed.
    • Use for smoke tests, ablations, and Kaggle 9h fast runs.
