# configs/model/constraints/strict.yaml
# ==============================================================================
# ⚖️ Physics Constraints — Strict Profile
# Strongest enforcement of symbolic + physical priors for diagnostics/science mode
# ==============================================================================

constraints:
  enforce_nonnegativity: true
  smoothness_weight: 0.020                  # strong smoothing
  fft_smoothness_weight: 0.005              # stronger suppression of high-freq noise
  asymmetry_weight: 0.002

  lensing:
    enabled: true
    bins: [120, 160]
    weight: 0.006                           # stronger penalty in lensing-sensitive bins

  molecular_fingerprint:
    enabled: true
    molecules: ["H2O", "CO2", "CH4", "NH3", "O3"]
    match_weight: 0.015
    false_positive_weight: 0.005

  calibration:
    nonnegativity_epsilon: 1.0e-8
    max_clip: 3.0                           # tighter clamp

  cycle_consistency:
    enabled: true
    weight: 0.005                           # forward–backward simulation validation

  diagnostics:
    log_violation_maps: true
    save_fft_plots: true
    export_json: "outputs/diagnostics/constraint_violations_strict.json"

  notes: |
    • Strict mode maximizes adherence to astrophysical realism.
    • Heavier smoothness & FFT penalties prevent noise artifacts.
    • Molecular priors expanded to include NH3 and O3 bands.
    • Lensing region weight doubled relative to default.
    • Cycle consistency ensures outputs remain consistent under simulation.
    • Use for deep diagnostics, interpretability, and publication-grade runs.
