# ==============================================================================
# SpectraMind V50 — Ablation Profile: LIGHT (fast CI / smoke)
# - Minimal epochs, small batch, CPU-friendly defaults
# - Disables heavy diagnostics (UMAP/t‑SNE/SHAP)
# - Exports lean leaderboard (Markdown/CSV only)
# - Suitable for PRs, nightly smoke, CI budget environments
# ==============================================================================

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

# -------------------------
# Global Reproducibility
# -------------------------
seed: 1337
deterministic: true
num_workers: 0

# -------------------------
# Curriculum Toggles
# -------------------------
curriculum:
  mae_pretrain: false
  contrastive:  false
  gll_finetune: true
  symbolic_finetune: false

masking:
  random: true
  block: false
  molecule_aware: false
  snr_aware: false

# -------------------------
# Loss Weights (coarse)
# -------------------------
loss:
  gll: 1.0
  fft_smoothness: 0.05
  asymmetry: 0.0
  nonnegativity: 0.05
  photonic_alignment: 0.0
  symbolic: 0.0
  entropy_reg: 0.0

# -------------------------
# Uncertainty Calibration
# -------------------------
uncertainty:
  temperature_scaling: true
  corel: false
  quantile: false
  conformal_prediction: false
  per_bin_eval: false

# -------------------------
# Symbolic Ablations
# -------------------------
symbolic:
  nonnegativity: true
  fft_smoothness: false
  asymmetry: false
  photonic_alignment: false
  violation_weight: 1.0
  normalize_losses: true
  trace_outputs: false

# -------------------------
# Runtime & Training (FAST)
# -------------------------
runtime:
  device: auto               # prefer cpu in CI; your runner can map 'auto' to cpu
  epochs: 1
  batch_size: 8
  mixed_precision: false
  checkpoint_interval: 0
  log_interval: 100
  max_runtime_hours: 1.5

# -------------------------
# Diagnostics Hooks (lean)
# -------------------------
diagnostics:
  enable_umap: false
  enable_tsne: false
  enable_shap: false
  enable_symbolic: true
  enable_fft: true
  gll_heatmap: true
  zscore_hist: false
  export_json: true
  export_png: true

# -------------------------
# Export / Leaderboard
# -------------------------
export:
  html: false
  markdown: true
  zip: false
  leaderboard_top_n: 3
  open_browser: false
  outdir: outputs/ablate_light

# -------------------------
# Hydra Sweep / Run dirs
# -------------------------
hydra:
  sweep:
    dir: outputs/multirun_light/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  run:
    dir: outputs/singlerun_light/${now:%Y-%m-%d_%H-%M-%S}
