# ==============================================================================
# SpectraMind V50 — Ablation Profile: HEAVY (deep analysis / offline)
# - More epochs + larger batch (9‑hour Kaggle envelope aware)
# - Enables full diagnostics (UMAP, t‑SNE, SHAP, symbolic, FFT)
# - Turns on advanced uncertainty calibration (temp scaling + COREL + conformal)
# - Exports full HTML/MD leaderboard and ZIP bundle of top‑N
# ==============================================================================

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

# -------------------------
# Global Reproducibility
# -------------------------
seed: 1337
deterministic: true
num_workers: 4

# -------------------------
# Curriculum Toggles
# -------------------------
curriculum:
  mae_pretrain: true
  contrastive:  true
  gll_finetune: true
  symbolic_finetune: true

masking:
  random: true
  block: true
  molecule_aware: true
  snr_aware: true

# -------------------------
# Loss Weights (richer)
# -------------------------
loss:
  gll: 1.0
  fft_smoothness: 0.25
  asymmetry: 0.08
  nonnegativity: 0.12
  photonic_alignment: 0.3
  symbolic: 0.6
  entropy_reg: 0.12

# -------------------------
# Uncertainty Calibration
# -------------------------
uncertainty:
  temperature_scaling: true
  corel: true
  quantile: true
  conformal_prediction: true
  per_bin_eval: true

# -------------------------
# Symbolic Ablations
# -------------------------
symbolic:
  nonnegativity: true
  fft_smoothness: true
  asymmetry: true
  photonic_alignment: true
  violation_weight: 1.0
  normalize_losses: true
  trace_outputs: true

# -------------------------
# Runtime & Training (DEEP)
# -------------------------
runtime:
  device: auto                 # resolve to cuda if available
  epochs: 6                    # tuned to respect 9‑hr Kaggle budget w/ mixed precision
  batch_size: 24
  mixed_precision: true
  checkpoint_interval: 1
  log_interval: 50
  max_runtime_hours: 8.5

# -------------------------
# Diagnostics Hooks (full)
# -------------------------
diagnostics:
  enable_umap: true
  enable_tsne: true
  enable_shap: true
  enable_symbolic: true
  enable_fft: true
  gll_heatmap: true
  zscore_hist: true
  export_json: true
  export_png: true

# -------------------------
# Export / Leaderboard
# -------------------------
export:
  html: true
  markdown: true
  zip: true
  leaderboard_top_n: 10
  open_browser: false
  outdir: outputs/ablate_heavy
  zip_name: outputs/ablate_heavy/topN_bundle.zip
  include:
    - "logs/v50_debug_log.md"
    - "logs/v50_event_log.jsonl"
    - "outputs/diagnostics/**"
    - "outputs/submission.csv"
    - "outputs/run_hash_summary_v50.json"

# -------------------------
# Hydra Sweep / Run dirs
# -------------------------
hydra:
  sweep:
    dir: outputs/multirun_heavy/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  run:
    dir: outputs/singlerun_heavy/${now:%Y-%m-%d_%H-%M-%S}
