# ==============================================================================
# SpectraMind V50 — DVC Pipeline
# Purpose:
#   • Defines full end-to-end pipeline for NeurIPS 2025 Ariel Challenge
#   • Stages: calibration → training → prediction → diagnostics → submission
#   • All configs handled by Hydra (YAMLs under /configs)
#   • Outputs tracked with DVC for reproducibility
#   • CI-safe: stages can be cached/skipped if inputs unchanged
# ==============================================================================

stages:

  # ───────────────────────── Data Calibration ─────────────────────────
  calibrate:
    cmd: >
      poetry run spectramind calibrate
      data/raw
      --out data/processed
      --config configs/data/calibration.yaml
    deps:
      - data/raw
      - src/pipeline/calibration_pipeline.py
      - configs/data/calibration.yaml
    outs:
      - data/processed

  # ───────────────────────── Model Training ─────────────────────────
  train:
    cmd: >
      poetry run spectramind train
      --config configs/training/config_v50.yaml
    deps:
      - data/processed
      - src/train_v50.py
      - configs/training/config_v50.yaml
    outs:
      - outputs/models/model_v50.pth
    metrics:
      - outputs/metrics/training.tsv
      - outputs/metrics/metrics.tsv
    plots:
      - outputs/metrics/training.tsv
      - outputs/metrics/metrics.tsv

  # ───────────────────────── Prediction / Inference ─────────────────────────
  predict:
    cmd: >
      poetry run spectramind predict
      --config configs/inference/predict_v50.yaml
    deps:
      - data/processed
      - outputs/models/model_v50.pth
      - src/predict_v50.py
      - configs/inference/predict_v50.yaml
    outs:
      - outputs/predictions/preds_v50.csv

  # ───────────────────────── Diagnostics & Symbolic Analysis ─────────────────────────
  diagnose:
    cmd: >
      poetry run spectramind diagnose dashboard
      --config configs/diagnostics/diagnose_v50.yaml
    deps:
      - outputs/predictions/preds_v50.csv
      - src/tools/generate_html_report.py
      - configs/diagnostics/diagnose_v50.yaml
    outs:
      - outputs/diagnostics/report_v50.html
      - outputs/diagnostics/diagnostic_summary.json
    plots:
      - outputs/diagnostics/binwise.csv
      - outputs/diagnostics/residuals.csv
      - outputs/diagnostics/fft.csv
      - outputs/diagnostics/fft_autocorr.csv
      - outputs/diagnostics/smoothness.csv
      - outputs/diagnostics/symbolic_violations.csv

  # ───────────────────────── Submission Packaging ─────────────────────────
  submit:
    cmd: >
      poetry run spectramind submit
      --config configs/submission/submit_v50.yaml
    deps:
      - outputs/predictions/preds_v50.csv
      - outputs/diagnostics/report_v50.html
      - src/cli_submit.py
      - configs/submission/submit_v50.yaml
    outs:
      - outputs/submissions/submission_v50.zip
    metrics:
      - outputs/metrics/leaderboard.tsv