# ==============================================================================
# SpectraMind V50 — Parameter Tracking for DVC
# ------------------------------------------------------------------------------
# Purpose:
#   • Single source of truth for pipeline hyperparameters
#   • Shared by Hydra configs, Typer CLI, and DVC stages
#   • Ensures NASA-grade reproducibility and run hash traceability
# ==============================================================================

training:
  epochs: 100                   # Full training length; override via CLI for quick runs
  batch_size: 48                # Larger batch size (fits Kaggle T4/V100 constraints)
  grad_accum_steps: 2           # Gradient accumulation for memory efficiency
  lr: 0.00025                   # Base learning rate (cosine schedule tuned)
  lr_scheduler: cosine
  warmup_epochs: 5              # Linear warmup to stabilize convergence
  optimizer: adamw
  weight_decay: 0.01
  early_stop_patience: 15       # Validation-based early stop
  checkpoint_interval: 5        # Save every N epochs
  log_interval: 50              # Log every N steps
  amp: true                     # Mixed precision (torch.cuda.amp)
  device: cuda
  seed: 1337                    # Deterministic RNG seeds across libs

model:
  encoder: fgs1_mamba           # Long-sequence Mamba encoder for FGS1
  gnn: airs_gnn                 # Graph Neural Network for AIRS spectra
  decoder: multi_scale_decoder  # Multi-scale μ spectrum decoder
  latent_dim: 256
  dropout: 0.1
  residual: true
  attention_fusion: true
  sigma_head: flow_uncertainty  # Flow-based σ head for uncertainty
  symbolic_loss: true
  symbolic_weight: 0.2          # Weight of symbolic logic constraints
  spectral_smoothness: true     # L2/FFT smoothness regularizer
  asymmetry_loss: true          # Penalize asymmetric spectra

data:
  fgs1_path: data/raw/fgs1/
  airs_path: data/raw/airs/
  calibration_path: data/processed/calibration/
  bins: 283
  split_seed: 2025
  snr_masking: true             # SNR-based masking (MAE pretraining)
  molecule_masking: true        # Mask known molecular bands in curriculum
  curriculum: true              # Epoch-based curriculum learning
  jitter_augmentation: true     # Pointing jitter augmentation for realism

calibration:
  enable: true
  method: corel                 # Conformal calibration (COREL)
  temperature_scaling: true
  coverage_target: 0.9
  per_bin: true
  plots: true
  save_csv: outputs/calibration/per_bin.csv

diagnostics:
  shap: true
  shap_topk: 20
  umap: true
  umap_dim: 2
  tsne: true
  tsne_dim: 2
  fft: true
  fft_autocorr: true
  symbolic: true
  symbolic_profiles: configs/symbolic/profiles.yaml
  conformal: true
  gll_heatmap: true
  smoothness_map: true
  violation_overlay: true
  html_report: outputs/diagnostics/report.html
  summary_json: outputs/diagnostics/diagnostic_summary.json

submission:
  bundle_dir: outputs/submission
  bundle_zip: outputs/submission/bundle.zip
  kaggle_format: true           # submission.csv is Kaggle-compliant
  include_diagnostics: true     # Attach diagnostics summary to bundle
  validate_before_zip: true     # Run selftest/validation before zipping
  versioned: true               # Version tag with run hash

ci:
  selftest: deep                # Full selftest before pipelines
  max_runtime: 9h               # Kaggle GPU runtime guardrail
  cache_datasets: true
  fail_on_violation: true       # Fail CI if symbolic violations exceed threshold
  log_jsonl: logs/ci_events.jsonl