name: "🚀 Feature Request"
description: "Propose a new idea, enhancement, or scientific/engineering capability for SpectraMind V50"
labels: ["feature", "enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request (SpectraMind V50)
        Thanks for taking the time to suggest an improvement.  
        Please fill out the details below so we can evaluate your request in line with our **NASA-grade reproducibility** and **CLI-first design**.

  - type: input
    id: summary
    attributes:
      label: "📝 Feature Summary"
      description: "Provide a concise title/summary of the feature you are requesting."
      placeholder: "Example: Add COREL calibration heatmap overlay in CLI diagnostics"

  - type: textarea
    id: motivation
    attributes:
      label: "💡 Motivation / Problem"
      description: |
        Why is this feature needed?  
        Describe the scientific, usability, or reproducibility gap this addresses.
      placeholder: "This would improve uncertainty calibration diagnostics and make symbolic overlays visible in HTML dashboards."

  - type: textarea
    id: proposed_solution
    attributes:
      label: "🛠️ Proposed Solution"
      description: |
        Describe your proposed implementation.  
        Include references to CLI commands, configs, symbolic modules, or pipelines.
      placeholder: |
        - Add new subcommand: `spectramind diagnose calibration-heatmap`
        - Integrate with Hydra configs under `configs/diagnostics/`
        - Log results in `v50_debug_log.md` and export to HTML dashboard

  - type: textarea
    id: alternatives
    attributes:
      label: "🔄 Alternatives Considered"
      description: "If you considered other options, describe them here."
      placeholder: "Alternatively, this could be implemented as a notebook-only utility, but that breaks reproducibility policy."

  - type: checkboxes
    id: impact
    attributes:
      label: "📈 Impact Areas"
      description: "Select all that apply."
      options:
        - label: "CLI functionality (`spectramind ...`)"
        - label: "Hydra configs / reproducibility"
        - label: "Scientific modeling / physics realism"
        - label: "Symbolic reasoning & logic engine"
        - label: "Diagnostics & visualization (HTML, plots, dashboards)"
        - label: "Pipeline integration (training, inference, calibration)"
        - label: "Other (please describe below)"

  - type: textarea
    id: related
    attributes:
      label: "🔗 Related Issues / References"
      description: "Link related issues, papers, or challenge rules here."
      placeholder: "#123, arXiv:2505.xxxxx, Kaggle forum link..."

  - type: dropdown
    id: priority
    attributes:
      label: "⏱️ Priority"
      description: "How urgent or impactful is this feature?"
      options:
        - "P1 — Critical (needed for Kaggle submission / core science)"
        - "P2 — High (important for diagnostics / dashboards)"
        - "P3 — Medium (quality-of-life improvement)"
        - "P4 — Low (nice to have)"

  - type: textarea
    id: additional
    attributes:
      label: "📂 Additional Context"
      description: |
        Provide any extra notes, sketches, or configuration examples.  
        Attach configs, logs, or pseudocode if useful.
      placeholder: |
        Example Hydra override:
        ```bash
        spectramind diagnose calibration-heatmap diagnostics.plot=true
        ```
