# ==============================================================================
# configs/env/ci.yaml — GitHub Actions / Continuous Integration Environment
# ------------------------------------------------------------------------------
# Purpose
#   Defines the CI/CD runtime environment for SpectraMind V50.
#   Ensures reproducible, Kaggle-parity builds inside GitHub Actions:
#     - Deterministic Python/CUDA stack
#     - Strict dependency pinning
#     - Security scans + SBOM export
#     - Submission validation (≤ 9h Kaggle runtime parity)
#
# Usage
#   spectramind test +env=ci
#   spectramind diagnose +env=ci
#
# Notes
#   - Mirrors `default.yaml` where possible
#   - Validates every PR/commit against MCP reproducibility rules
#   - CI workflows live in `.github/workflows/`
# ==============================================================================

# ----------------------------
# Base Inheritance
# ----------------------------
defaults:
  - override /env: default

# ----------------------------
# CI Runner Constraints
# ----------------------------
ci:
  provider: "github-actions"
  os: "ubuntu-latest"
  python_setup: "actions/setup-python@v5"
  cache: true
  reproducibility_checks: true
  sbom: true
  security_scans:
    - trivy
    - pip-audit
    - bandit
  runners:
    cpu: true
    gpu: false      # GPUs not available on GitHub-hosted runners
  runtime_limit_minutes: 120 # typical CI max time per job

# ----------------------------
# Python & Package Management
# ----------------------------
python:
  version: "3.10.13"       # CI uses the same baseline as Kaggle/local
  package_manager: poetry
  poetry_lock: "poetry.lock"
  pyproject: "pyproject.toml"

# ----------------------------
# CUDA / GPU Configuration
# ----------------------------
cuda:
  version: "11.8"          # Pinned for parity with Kaggle/Docker
  cudnn: "8.7.0"
  deterministic: true
  benchmark: false
  allow_tf32: false

# ----------------------------
# Logging & Tracking
# ----------------------------
logging:
  level: "INFO"
  handlers: ["console"]
  log_file: "logs/ci_build.log"
  mlflow:
    enabled: false          # Disabled in CI
  wandb:
    enabled: false          # Disabled in CI

# ----------------------------
# Hydra Integration
# ----------------------------
hydra:
  run:
    dir: outputs/ci/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multiruns/ci/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true

# ----------------------------
# Dependencies
# ----------------------------
dependencies:
  core:
    - torch==2.2.2+cpu      # CPU-only wheels for CI speed
    - numpy==1.26.4
    - pandas==2.2.2
    - scipy==1.13.1
    - scikit-learn==1.5.0
    - hydra-core==1.3.2
    - omegaconf==2.3.0
  dev:
    - pytest==8.2.2
    - black==24.4.2
    - isort==5.13.2
    - flake8==7.0.0
    - mypy==1.10.0
    - bandit==1.7.9
  ci:
    - pip-audit==2.7.2
    - trivy==0.54.1          # installed via container step
    - cyclonedx-bom==4.2.0   # SBOM export
  viz:
    - matplotlib==3.9.1
    - seaborn==0.13.2
    - plotly==5.22.0

# ----------------------------
# DVC / Data Versioning
# ----------------------------
dvc:
  enabled: true
  remote: "gcs://spectramind-v50-ci"
  cache: ".dvc/cache"
  config: ".dvc/config"

# ----------------------------
# Containerization
# ----------------------------
docker:
  enabled: true
  base_image: "python:3.10-slim"
  pinned_versions: true

# ----------------------------
# Validation (Self-Test)
# ----------------------------
selftest:
  check_python: true
  check_cuda: true
  check_poetry: true
  check_dvc: true
  check_sbom: true
  check_security: true
  fail_fast: true