# ==============================================================================
# configs/env/kaggle.yaml — Kaggle Runtime Environment (SpectraMind V50)
# ------------------------------------------------------------------------------
# Purpose
#   Defines Kaggle-specific runtime environment for the NeurIPS 2025 Ariel Data
#   Challenge. Mirrors `default.yaml` with overrides to comply with Kaggle’s
#   restrictions (no internet, ≤ 9h runtime, GPU-only execution).
#
# Usage
#   spectramind train +env=kaggle
#   spectramind calibrate +env=kaggle
#
# Notes
#   - Kaggle auto-mounts competition data under /kaggle/input/
#   - Internet is disabled during execution
#   - Runtime limit ≈ 9h across ~1100 planets
# ==============================================================================

# ----------------------------
# Base Inheritance
# ----------------------------
defaults:
  - override /env: default

# ----------------------------
# Kaggle Environment Constraints
# ----------------------------
kaggle:
  runtime_limit_hours: 9
  internet: false
  gpu: true
  accelerator: "T4|A100|L4"   # Kaggle-provided GPUs
  input_dir: "/kaggle/input"
  output_dir: "/kaggle/working"
  datasets:
    - "neurips-2025-ariel-data-challenge"  # Competition dataset
    - "v50-weights"                        # Pretrained weights/artifacts
    - "v50-runtime"                        # Optional runtime wheel/source

# ----------------------------
# Python & Package Management
# ----------------------------
python:
  version: "3.10.13"       # Matches Kaggle base image
  package_manager: poetry  # Poetry to enforce lockfile
  poetry_lock: "poetry.lock"
  pyproject: "pyproject.toml"

# ----------------------------
# CUDA / GPU Configuration
# ----------------------------
cuda:
  version: "11.8"          # Kaggle runtime default
  cudnn: "8.7.0"
  deterministic: true
  benchmark: false
  allow_tf32: false

# ----------------------------
# Logging & Tracking
# ----------------------------
logging:
  level: "INFO"
  handlers: ["console", "file"]
  log_file: "/kaggle/working/spectramind_v50.log"
  mlflow:
    enabled: false          # Disabled in Kaggle (no server / internet)
  wandb:
    enabled: false          # Disabled in Kaggle

# ----------------------------
# Hydra Integration
# ----------------------------
hydra:
  run:
    dir: /kaggle/working/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: /kaggle/working/multiruns/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: true

# ----------------------------
# Dependencies
# ----------------------------
dependencies:
  core:
    - torch==2.2.2
    - torchvision==0.17.2
    - torchaudio==2.2.2
    - torch_geometric==2.5.3
    - numpy==1.26.4
    - pandas==2.2.2
    - scipy==1.13.1
    - scikit-learn==1.5.0
    - hydra-core==1.3.2
    - omegaconf==2.3.0
  viz:
    - matplotlib==3.9.1
    - seaborn==0.13.2
    - plotly==5.22.0

# ----------------------------
# DVC / Data Versioning
# ----------------------------
dvc:
  enabled: false            # Kaggle disallows external remotes
  remote: null
  cache: null
  config: null

# ----------------------------
# Containerization (Not used)
# ----------------------------
docker:
  enabled: false

# ----------------------------
# Validation (Self-Test)
# ----------------------------
selftest:
  check_python: true
  check_cuda: true
  check_kaggle_mounts: true
  fail_fast: true