# File logger — writes to logs/v50_debug.log
logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    detailed:
      format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    file:
      class: logging.FileHandler
      formatter: detailed
      filename: logs/v50_debug.log
      mode: a
  root:
    level: DEBUG
    handlers: [file]