# .github/workflows/ablation.yml
# ==============================================================================
# SpectraMind V50 — Ablation Runner (Hydra-safe, Reproducible)
# - Presets come from configs/ablation/ablation_v50.yaml
# - PR: runs ONLY fast_eval (≤ ~5–10 min)
# - Nightly / Manual: runs selected preset matrix; optional Hydra multirun (-m)
# - Artifacts: logs + outputs under outputs/ablations/<preset>/
# - Caching: pip/poetry/.venv, strict bash, explicit timeouts, concurrency guard
# ==============================================================================

name: Ablations

on:
  pull_request:
    branches: ["**"]
    paths:
      - "configs/ablation/**"
      - "configs/**"
      - "src/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "!**/*.md"
  schedule:
    - cron: "45 2 * * 2,5"   # Tue/Fri @ 02:45 UTC
  workflow_dispatch:
    inputs:
      presets:
        description: "Comma-separated presets to run (e.g. default,light,strict_symbolic,fast_eval,gnn_ssm_ablate)"
        required: false
        default: "default,light"
      multirun:
        description: "Enable Hydra multirun grid (+grid.enable=true) for selected presets"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]
      extra_overrides:
        description: "Hydra overrides (e.g., +training.seed=1337 +training.epochs=1)"
        required: false
        type: string

permissions:
  contents: read
  actions: read
  checks: read

concurrency:
  group: ablations-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euxo pipefail

env:
  PY: "3.12"
  POETRY_VERSION: "1.8.3"
  HYDRA_CFG: "configs/ablation/ablation_v50.yaml"
  OUTDIR: "outputs/ablations"

jobs:
  # tiny helper to decide which presets to keep in matrix
  select:
    name: Select Presets
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      presets: ${{ steps.sel.outputs.presets }}
      multirun: ${{ steps.sel.outputs.multirun }}
      extra: ${{ steps.sel.outputs.extra }}
    steps:
      - id: sel
        run: |
          # presets (from dispatch or defaults)
          INPUT_PRESETS="${{ github.event.inputs.presets }}"
          if [ -z "$INPUT_PRESETS" ]; then
            if [ "${{ github.event_name }}" = "pull_request" ]; then
              PRESETS="fast_eval"
            else
              PRESETS="default,light"
            fi
          else
            PRESETS="$INPUT_PRESETS"
          fi
          echo "presets=$PRESETS" >> "$GITHUB_OUTPUT"

          # multirun flag (default false)
          MR="${{ github.event.inputs.multirun }}"
          if [ -z "$MR" ]; then MR="false"; fi
          echo "multirun=$MR" >> "$GITHUB_OUTPUT"

          # extra overrides (optional)
          EXTRA="${{ github.event.inputs.extra_overrides }}"
          echo "extra=${EXTRA}" >> "$GITHUB_OUTPUT"

  ablate:
    name: Run Ablation Presets • ${{ matrix.preset }}
    needs: select
    runs-on: ubuntu-latest
    timeout-minutes: 90

    strategy:
      fail-fast: false
      matrix:
        preset: [default, light, strict_symbolic, fast_eval, gnn_ssm_ablate]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.PY }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY }}
          cache: "pip"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install "poetry==${POETRY_VERSION}"

      - name: Configure in-project venv (cache-friendly)
        run: |
          poetry config virtualenvs.in-project true
          poetry config installer.max-workers 10

      - name: Cache deps (pip/poetry/.venv)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
            ./.venv
          key: ablate-${{ runner.os }}-py${{ env.PY }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ablate-${{ runner.os }}-py${{ env.PY }}-

      - name: Install project (no dev extras)
        run: |
          poetry install --no-interaction --no-ansi --without dev

      - name: Skip preset (not selected for this event)
        if: ${{ !contains(needs.select.outputs.presets, matrix.preset) }}
        run: |
          echo "Preset '${{ matrix.preset }}' not in list '${{ needs.select.outputs.presets }}' — skipping."
          printf "skipped\n" > "skip_${{ matrix.preset }}.txt"

      - name: Enforce PR fast path
        if: ${{ github.event_name == 'pull_request' && matrix.preset != 'fast_eval' && contains(needs.select.outputs.presets, matrix.preset) }}
        run: |
          echo "PR fast path: only 'fast_eval' allowed — skipping '${{ matrix.preset }}'."
          printf "pr-fast-skip\n" > "skip_${{ matrix.preset }}.txt"

      - name: Show CLI banner / versions
        if: ${{ contains(needs.select.outputs.presets, matrix.preset) && !(github.event_name == 'pull_request' && matrix.preset != 'fast_eval') }}
        run: |
          poetry run spectramind --version || true
          python -V
          poetry -V

      - name: Run ablation preset
        if: ${{ contains(needs.select.outputs.presets, matrix.preset) && !(github.event_name == 'pull_request' && matrix.preset != 'fast_eval') }}
        run: |
          set -eo pipefail
          mkdir -p "${OUTDIR}"
          EXTRA_FLAGS=""
          if [ "${{ needs.select.outputs.multirun }}" = "true" ]; then
            EXTRA_FLAGS="+grid.enable=true -m"
          fi
          USER_OVERRIDES="${{ needs.select.outputs.extra }}"
          echo "::group::Ablation ${{ matrix.preset }}"
          poetry run spectramind ablate \
            ablation=${{ matrix.preset }} \
            --config-path configs/ablation \
            --config-name ablation_v50 \
            export.outdir="${OUTDIR}/${{ matrix.preset }}" \
            ${EXTRA_FLAGS} ${USER_OVERRIDES} 2>&1 | tee "ablate_${{ matrix.preset }}.log"
          echo "::endgroup::"

      - name: Summarize last 60 log lines
        if: always()
        run: |
          {
            echo "### Ablation — \`${{ matrix.preset }}\`"
            if [ -f "ablate_${{ matrix.preset }}.log" ]; then
              echo
              echo "<details><summary>Last 60 lines</summary>"
              echo
              tail -n 60 "ablate_${{ matrix.preset }}.log" | sed -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
              echo
              echo "</details>"
            else
              echo
              echo "_No log produced (skipped/failed before run step)._"
            fi
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Collect artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ablation-${{ matrix.preset }}
          path: |
            skip_${{ matrix.preset }}.txt
            ablate_${{ matrix.preset }}.log
            outputs/ablations/${{ matrix.preset }}/**
          if-no-files-found: ignore
          retention-days: 10
```
