# ==============================================================================
# SpectraMind V50 — Ablation Config (Hydra-safe, Full-spectrum)
# Neuro-Symbolic, Physics-Informed AI Pipeline
# NeurIPS 2025 Ariel Data Challenge
#
# Purpose:
#   Defines structured ablation toggles for curriculum, loss weights,
#   uncertainty calibration, symbolic rules, runtime diagnostics, and exports.
#   Used by auto_ablate_v50.py and cli_ablate.py.
#
# Usage:
#   poetry run spectramind ablate ablation=default
#   poetry run spectramind ablate ablation=light --multirun
# ==============================================================================

defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - _self_

# -------------------------
# Global Reproducibility
# -------------------------
seed: 1337
deterministic: true
num_workers: 4

# -------------------------
# Curriculum Toggles
# -------------------------
curriculum:
  mae_pretrain: true              # Masked Autoencoder pretraining
  contrastive: true               # Contrastive fine-tuning
  gll_finetune: true              # Gaussian log-likelihood final phase
  symbolic_finetune: true         # Symbolic rule integration

masking:
  random: true
  block: false
  molecule_aware: true
  snr_aware: true

# -------------------------
# Loss Weights (per-task)
# -------------------------
loss:
  gll: 1.0
  fft_smoothness: 0.2
  asymmetry: 0.1
  nonnegativity: 0.1
  photonic_alignment: 0.3
  symbolic: 0.5
  entropy_reg: 0.1

# -------------------------
# Uncertainty Calibration
# -------------------------
uncertainty:
  temperature_scaling: true
  corel: true
  quantile: false
  conformal_prediction: true
  per_bin_eval: true

# -------------------------
# Symbolic Ablations
# -------------------------
symbolic:
  nonnegativity: true
  fft_smoothness: true
  asymmetry: true
  photonic_alignment: true
  violation_weight: 1.0
  normalize_losses: true
  trace_outputs: true

# -------------------------
# Runtime & Training
# -------------------------
runtime:
  device: auto                   # cpu | cuda | mps | auto
  epochs: 3
  batch_size: 16
  mixed_precision: true
  checkpoint_interval: 1
  log_interval: 50
  max_runtime_hours: 9

# -------------------------
# Diagnostics Hooks
# -------------------------
diagnostics:
  enable_umap: true
  enable_tsne: true
  enable_shap: true
  enable_symbolic: true
  enable_fft: true
  gll_heatmap: true
  zscore_hist: true
  export_json: true
  export_png: true

# -------------------------
# Export / Leaderboard
# -------------------------
export:
  html: true
  markdown: true
  zip: true
  leaderboard_top_n: 5
  open_browser: false
  outdir: outputs/ablations

# -------------------------
# Hydra Overrides (sweeps)
# -------------------------
hydra:
  sweep:
    dir: outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  run:
    dir: outputs/singlerun/${now:%Y-%m-%d_%H-%M-%S}
