name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        run: pipx install poetry==1.8.3
      - name: Install deps
        run: |
          poetry install --no-interaction
          poetry run pre-commit install
      - name: Lint (pre-commit)
        run: poetry run pre-commit run --all-files
      - name: Tests
        run: poetry run pytest -q
      - name: "Smoke: CLI selftest (dry-run)"
        run: poetry run python -m asa.cli selftest --dry-run
