name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Install deps
        run: |
          poetry install --no-interaction
          poetry run pre-commit install

      - name: Install torch (CPU)
        run: poetry run pip install --upgrade --index-url https://download.pytorch.org/whl/cpu torch

      - name: Lint (pre-commit)
        run: poetry run pre-commit run --all-files

      - name: Tests
        run: poetry run pytest -q

      - name: "Smoke: CLI selftest (dry-run)"
        run: poetry run python -m asa.cli selftest --dry-run

      # ---- End-to-end smoke on CPU ----
      - name: Train (toy)
        run: poetry run asa train

      - name: Predict (283 bins)
        run: poetry run asa predict

      - name: Validate submission.csv (283 bins)
        run: poetry run python scripts/validate_submission.py outputs/submission.csv

      - name: Calibrate (temperature scaling)
        run: poetry run python -m asa.calib.temperature
        continue-on-error: true

      - name: Generate diagnostics report (HTML)
        run: poetry run python -m asa.diagnostics.report
        continue-on-error: true

      - name: Upload artifacts (report & preds)
        uses: actions/upload-artifact@v4
        with:
          name: e2e-artifacts
          path: |
            outputs/submission.csv
            outputs/submission_calibrated.csv
            outputs/report.html
            outputs/preds.pt
            outputs/preds_calibrated.pt
          if-no-files-found: ignore
