# .github/workflows/diagnostics.yml
# SpectraMind V50 — Diagnostics Workflow
# Generates HTML dashboards & diagnostic artifacts (UMAP/t‑SNE*, GLL heatmaps,
# SHAP*, symbolic overlays). Defaults to a CI‑safe "light" run; you can supply
# extra Hydra overrides in workflow_dispatch. (*heavy diagnostics may be skipped)

name: diagnostics

on:
  workflow_dispatch:
    inputs:
      extra_overrides:
        description: "Hydra overrides (e.g., +data.split=toy +diagnostics.light=true)"
        type: string
        required: false
        default: "+diagnostics.light=true +data.split=toy"
      run_ablation:
        description: "Also run fast ablation and attach leaderboard?"
        type: choice
        options: ["false", "true"]
        required: false
        default: "false"
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  schedule:
    # Weekly snapshot (Sundays 07:00 UTC)
    - cron: "0 7 * * 0"

permissions:
  contents: read

concurrency:
  group: diagnostics-${{ github.ref }}
  cancel-in-progress: true

env:
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  POETRY_NO_INTERACTION: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PIP_NO_PYTHON_VERSION_WARNING: "1"
  TRANSFORMERS_OFFLINE: "1"
  HF_HUB_OFFLINE: "1"
  HYDRA_FULL_ERROR: "1"
  DEFAULT_OVERRIDES: "+diagnostics.light=true +data.split=toy"
  DEVICE: "cpu"
  POETRY_VERSION: "1.8.3"

jobs:
  build:
    name: Diagnostics • py${{ matrix.python }}
    runs-on: ubuntu-latest
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        python: ["3.11", "3.12"]

    env:
      DIAG_DIR: "outputs/diagnostics"
      ARTIFACT_DIR: "artifacts/diagnostics/py${{ matrix.python }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Python ${{ matrix.python }}
        id: setup-py
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install "poetry==${{ env.POETRY_VERSION }}"

      - name: Cache Poetry & venv
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
            .venv
          key: poetry-${{ runner.os }}-${{ matrix.python }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-${{ runner.os }}-${{ matrix.python }}-

      - name: Install dependencies
        run: |
          poetry env use "${{ steps.setup-py.outputs.python-path }}"
          poetry install --no-root

      - name: Versions
        run: |
          python --version
          poetry --version
          poetry run python - <<'PY'
import sys, platform, importlib, json
info={"platform": platform.platform(), "python": sys.version.replace("\n"," ")}
for m in ("torch","numpy","pandas","matplotlib"):
    try:
        mod=importlib.import_module(m)
        info[m]=getattr(mod,"__version__", "n/a")
    except Exception:
        info[m]="not installed"
print(json.dumps(info, indent=2))
PY

      - name: Validate .env (safe no‑op if missing)
        run: |
          if [ -f scripts/validate_env.py ]; then
            poetry run python scripts/validate_env.py
          else
            echo "No scripts/validate_env.py — skipping."
          fi

      - name: Optional DVC pull
        run: |
          python -m pip install --upgrade "dvc[all]" || python -m pip install --upgrade dvc
          dvc --version || true
          dvc pull --run-cache --force || true

      - name: Prepare artifact folders
        run: |
          mkdir -p "${ARTIFACT_DIR}" "${DIAG_DIR}"

      - name: CLI selftest (fast)
        run: |
          poetry run spectramind selftest --fast

      - name: Train minimal model for diagnostics (fast)
        run: |
          OVERRIDES="${DEFAULT_OVERRIDES} ${{ inputs.extra_overrides }}"
          echo "Using overrides: ${OVERRIDES}"
          poetry run spectramind train +training.epochs=1 ${OVERRIDES} --device ${DEVICE} --outdir "${ARTIFACT_DIR}"

      - name: Generate diagnostics — smoothness
        run: |
          poetry run spectramind diagnose smoothness --outdir "${ARTIFACT_DIR}"

      - name: Generate diagnostics — dashboard (HTML)
        run: |
          poetry run spectramind diagnose dashboard --no-umap --no-tsne --outdir "${ARTIFACT_DIR}" || \
          poetry run spectramind diagnose dashboard --outdir "${ARTIFACT_DIR}" || true

      - name: Node/Mermaid diagrams (optional)
        run: |
          if command -v npm >/dev/null 2>&1 && [ -f package.json ]; then
            make node-ci
            make node-diagrams
            mkdir -p "${ARTIFACT_DIR}/diagrams"
            cp -a outputs/diagrams/* "${ARTIFACT_DIR}/diagrams/" 2>/dev/null || true
          else
            echo "Skipping node/mermaid (npm or package.json not found)"
          fi

      - name: Collate artifacts
        run: |
          for p in \
            "${DIAG_DIR}"/*.html \
            "${DIAG_DIR}"/*.png \
            "${DIAG_DIR}"/*.svg \
            "${DIAG_DIR}"/*.json \
            "${DIAG_DIR}"/*.csv \
            "${ARTIFACT_DIR}"/*.html \
            "${ARTIFACT_DIR}"/*.png \
            "${ARTIFACT_DIR}"/*.svg \
            "${ARTIFACT_DIR}"/*.json \
            "${ARTIFACT_DIR}"/*.csv \
          ; do
            [ -f "$p" ] && cp -v "$p" "${ARTIFACT_DIR}/" || true
          done
          # optional logs & run hash
          [ -f logs/v50_debug_log.md ] && cp -v logs/v50_debug_log.md "${ARTIFACT_DIR}/" || true
          [ -f outputs/run_hash_summary_v50.json ] && cp -v outputs/run_hash_summary_v50.json "${ARTIFACT_DIR}/" || true

      - name: Summarize diagnostics run
        run: |
          {
            echo "SpectraMind V50 — Diagnostics Summary"
            date
            echo "Python: ${{ matrix.python }}"
            echo "Device: ${DEVICE}"
            echo "Artifacts:"
            ls -lh "${ARTIFACT_DIR}" || true
          } > "${ARTIFACT_DIR}/summary.txt"
          cat "${ARTIFACT_DIR}/summary.txt"

      - name: Upload diagnostics artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics-py${{ matrix.python }}
          path: ${{ env.ARTIFACT_DIR }}
          if-no-files-found: warn
          retention-days: 30

  ablate:
    name: Ablation Leaderboard (scheduled/manual)
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 45
    if: |
      github.event_name == 'schedule' ||
      (github.event_name == 'workflow_dispatch' && inputs.run_ablation == 'true')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install "poetry==${{ env.POETRY_VERSION }}"
          poetry install --no-root
      - name: Run ablation (fast grid)
        run: |
          poetry run spectramind ablate -m ablate.sweeper=basic +ablate.search=v50_fast_grid ablation=ablation_light || true
      - name: Upload ablation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ablation-leaderboard
          path: |
            outputs/ablate/leaderboard.csv
            outputs/ablate/**
          if-no-files-found: ignore
          retention-days: 30

  aggregate:
    name: Aggregate Diagnostics Index
    needs: [build]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download diagnostics artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: diagnostics-py*
          merge-multiple: true

      - name: Build aggregated index
        run: |
          mkdir -p aggregated
          {
            echo "# SpectraMind V50 — Diagnostics Index"
            echo ""
            echo "_Generated: $(date -u)_"
            echo ""
            find artifacts -type f -maxdepth 5 | sed 's/^/- /'
          } > aggregated/DIAGNOSTICS_INDEX.md
          echo "Created aggregated/DIAGNOSTICS_INDEX.md"
          head -n 50 aggregated/DIAGNOSTICS_INDEX.md || true

      - name: Upload aggregated index
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics-aggregated
          path: aggregated/DIAGNOSTICS_INDEX.md
          if-no-files-found: warn
          retention-days: 30