# .github/workflows/docs.yml
# GitHub Actions workflow for building and deploying SpectraMind V50 documentation
# - Uses MkDocs with Material theme
# - Publishes to GitHub Pages
# - Runs on pushes to main and on PRs for validation
# - Ensures links and syntax are valid

name: docs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install MkDocs & plugins
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs \
            mkdocs-material \
            mkdocs-awesome-pages-plugin \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-section-index \
            mkdocs-glightbox \
            mkdocs-mermaid2-plugin \
            mkdocs-minify-plugin \
            mkdocs-redirects \
            mkdocs-include-markdown-plugin \
            linkchecker

      - name: Build site
        run: |
          if [ -f mkdocs.yml ]; then
            mkdocs build --strict --site-dir site
          else
            echo "mkdocs.yml not found — skipping docs build." && exit 1
          fi

      - name: Link check
        run: |
          linkchecker --ignore-url "https://fonts.gstatic.com" site/index.html || true

      - name: Upload Pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    name: Deploy Documentation
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
