# .github/workflows/lint.yml
# GitHub Actions workflow to enforce code quality and style for SpectraMind V50
# - Runs pre-commit hooks
# - Checks Python code with ruff, black, isort, mypy
# - Validates YAML and Markdown
# - Runs on all pushes and PRs

name: lint

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Style Checks
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            pre-commit \
            ruff \
            black \
            isort \
            mypy \
            yamllint \
            markdownlint-cli2

      - name: Run pre-commit hooks on all files
        run: |
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure

      - name: Ruff check
        run: |
          ruff check . --exit-non-zero-on-fix

      - name: Black check
        run: |
          black --check --diff .

      - name: isort check
        run: |
          isort --check-only --diff .

      - name: Mypy type checking
        run: |
          mypy src || true

      - name: YAML lint
        run: |
          yamllint .

      - name: Markdown lint
        run: |
          markdownlint-cli2 '**/*.md' --ignore node_modules || true
