name: lint

on:
  push:
    branches: ["**"]
    paths-ignore:
      - "data/**"
      - "outputs/**"
      - "logs/**"
      - "**/*.ipynb_checkpoints/**"
  pull_request:
    branches: ["**"]
    paths-ignore:
      - "data/**"
      - "outputs/**"
      - "logs/**"
      - "**/*.ipynb_checkpoints/**"
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Style (pre-commit)
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      PYTHONDONTWRITEBYTECODE: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_PYTHON_VERSION_WARNING: "1"
      # keep output readable in CI
      PRE_COMMIT_COLOR: "always"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Cache pre-commit env
        id: cache-precommit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: precommit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            precommit-${{ runner.os }}-

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Prepare artifacts dir
        run: mkdir -p artifacts

      - name: Run pre-commit (all hooks)
        # Run once, capture logs for summary & artifacts; don't fail the job yet
        run: |
          set -o pipefail
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure | tee artifacts/precommit.txt || echo "::warning::pre-commit found issues"
      
      - name: Rerun to fail on remaining issues
        # Second run ensures the job fails if issues remain (idempotent hooks may fix on first pass)
        run: |
          pre-commit run --all-files --show-diff-on-failure

      - name: Build lint summary
        if: always()
        run: |
          SUMMARY="artifacts/lint-summary.md"
          echo "# Lint & Style Summary" > "$SUMMARY"
          echo "" >> "$SUMMARY"
          echo "- Repo: $GITHUB_REPOSITORY" >> "$SUMMARY"
          echo "- Commit: $GITHUB_SHA" >> "$SUMMARY"
          echo "- Run ID: $GITHUB_RUN_ID" >> "$SUMMARY"
          echo "" >> "$SUMMARY"
          echo "### pre-commit (consolidated output)" >> "$SUMMARY"
          if [ -s artifacts/precommit.txt ]; then
            echo "" >> "$SUMMARY"
            echo '```' >> "$SUMMARY"
            awk 'NR<=400{print} NR==401{print "...(truncated)"}' artifacts/precommit.txt >> "$SUMMARY"
            echo '```' >> "$SUMMARY"
          else
            echo "✅ Clean (no output)" >> "$SUMMARY"
          fi
          echo "" >> "$SUMMARY"
          echo "## Overall Status" >> "$SUMMARY"
          if grep -qsE "Failed|^fail|❌|error|failing" artifacts/precommit.txt; then
            echo "- **Result:** ❌ Lint issues detected. See details above." >> "$SUMMARY"
          else
            echo "- **Result:** ✅ All checks passed." >> "$SUMMARY"
          fi
          cat "$SUMMARY" >> "$GITHUB_STEP_SUMMARY"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-artifacts
          path: artifacts/
          if-no-files-found: ignore
          retention-days: 14