# .github/workflows/lint.yml
# SpectraMind V50 — Lint & Style Workflow
# Neuro-Symbolic, Physics-Informed AI Pipeline
# Enforces pre-commit hooks, code quality, typing, YAML/Markdown validation.
# Outputs artifacts for diagnostics dashboard integration.

name: lint

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Style Checks
    runs-on: ubuntu-latest
    timeout-minutes: 25

    env:
      PYTHON_DEFAULT: "3.11"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_NO_PYTHON_VERSION_WARNING: "1"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_DEFAULT }}
          cache: "pip"

      - name: Install linting stack
        run: |
          python -m pip install --upgrade pip
          pip install \
            pre-commit \
            ruff \
            black \
            isort \
            mypy \
            yamllint \
            markdownlint-cli2

      - name: Run pre-commit hooks on all files
        run: |
          pre-commit install
          pre-commit run --all-files --show-diff-on-failure

      - name: Ruff check (Python linter, fast)
        run: |
          ruff check . --exit-non-zero-on-fix --show-fixes

      - name: Black check (formatting)
        run: |
          black --check --diff .

      - name: isort check (import ordering)
        run: |
          isort --check-only --diff .

      - name: MyPy type checking
        run: |
          mkdir -p artifacts
          mypy src || true
        continue-on-error: true

      - name: YAML lint
        run: |
          yamllint . || true

      - name: Markdown lint
        run: |
          markdownlint-cli2 '**/*.md' --ignore node_modules || true

      - name: Archive lint artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lint-artifacts
          path: artifacts/
          if-no-files-found: ignore
          retention-days: 14