name: Release (tagged, gated by CI)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write  # create releases & upload assets

jobs:
  ci-smoke:
    name: CI Smoke (CPU)
    runs-on: ubuntu-latest
    timeout-minutes: 35

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Install deps
        run: |
          poetry install --no-interaction
          poetry run pre-commit install

      - name: Install torch (CPU)
        run: poetry run pip install --upgrade --index-url https://download.pytorch.org/whl/cpu torch

      - name: Lint
        run: poetry run pre-commit run --all-files

      - name: Tests
        run: poetry run pytest -q

      - name: Train (toy)
        run: poetry run asa train

      - name: Predict (283 bins)
        run: poetry run asa predict

      - name: Validate submission.csv (283 bins)
        run: poetry run python scripts/validate_submission.py outputs/submission.csv

      - name: Calibrate (temperature)
        run: poetry run python -m asa.calib.temperature

      - name: Diagnostics report (HTML)
        run: poetry run python -m asa.diagnostics.report

      - name: Collect artifacts
        run: |
          mkdir -p release_artifacts
          cp -f outputs/submission.csv release_artifacts/ || true
          cp -f outputs/submission_calibrated.csv release_artifacts/ || true
          cp -f outputs/report.html release_artifacts/ || true
          cp -f outputs/preds.pt release_artifacts/ || true
          cp -f outputs/preds_calibrated.pt release_artifacts/ || true

      - name: Upload artifacts (for next job)
        uses: actions/upload-artifact@v4
        with:
          name: release-bundle
          path: release_artifacts/*
          if-no-files-found: error

  build-and-release:
    name: Build GitHub Release
    runs-on: ubuntu-latest
    needs: [ci-smoke]   # <-- gate: only publish if CI smoke passed
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download artifacts from CI smoke
        uses: actions/download-artifact@v4
        with:
          name: release-bundle
          path: release_artifacts

      - name: Create GitHub Release (attach artifacts)
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          generate_release_notes: true
          files: |
            release_artifacts/*
